steps:
  # Step 1: Build Container using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:${_ENV}', '.']
    id: Docker Build

  # Step 2: Push Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:${_ENV}']
    id: Push Image

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'recruithub-${_ENV}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$BRANCH_NAME:${_ENV}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'JDBC_DATABASE_URL=${_JDBC_DATABASE_URL},JDBC_DATABASE_USERNAME=${_JDBC_DATABASE_USERNAME},JDBC_DATABASE_PASSWORD=${_JDBC_DATABASE_PASSWORD},MAIL_USERNAME=${_MAIL_USERNAME},MAIL_PASSWORD=${_MAIL_PASSWORD}'
    id: Deploy

images:
  - 'gcr.io/$PROJECT_ID/$BRANCH_NAME:${_ENV}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _ENV: "dev"
  _JDBC_DATABASE_URL: "jdbc:postgresql://dpg-cvpaoipr0fns73806tc0-a/recruitment_mjz9"
  _JDBC_DATABASE_USERNAME: "recruitment_mjz9_user"
  _JDBC_DATABASE_PASSWORD: "1Jmnwzlbjd8RwWyzOE97H0Lz8Q3iIOXV"
  _MAIL_USERNAME: "ritwik.kam25@gmail.com"
  _MAIL_PASSWORD: "jaye znmj vqbd tdnx"